# PostgreSQL 
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/cashcarddb}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Spring Data JDBC
spring.sql.init.mode=always

# Logging
logging.level.org.springframework.security=INFO
logging.level.example.cashcard=DEBUG

server.port=8080
